- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 18000 #5 hrs
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 7200 #2 hrs
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 36000 #10 hrs
    - !type:OverallPlaytimeRequirement
      time: 54000 #15 hrs
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - External
  - Cryogenics
  - External # goobstation

- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetAltCargo # Goobstation
    eyes: ClothingEyesGlassesSunglasses
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
